FROM chatwoot/chatwoot:latest

COPY . /app/
WORKDIR /app

RUN bundle install --without development test
RUN yarn install --production
RUN RAILS_ENV=production bundle exec rake assets:precompile

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
